# To be tested
version: "3.7"
services:
    atlassian-crowd:
        container_name: atlassianCrowdProd

        environment:
            VIRTUAL_HOST: ${HOST:?Missing environment variable see readme}
            VIRTUAL_PORT: 8095
            LETSENCRYPT_HOST: ${HOST:?Missing environment variable see readme}
            ATL_PROXY_NAME: ${HOST:?Missing environment variable see readme}
            ATL_PROXY_PORT: 443
            ATL_TOMCAT_SECURE: 1

            networks:
                - default
                - nginxproxynet

        ports:
            - 8095

    postgres:
        ports:
            - 5432

        container_name: atlassianCrowdPostgresqlProd

        environment:
            FORCE_COLOR: 1
            POSTGRES_USER: ${PG_USER-atlassianCrowdProd}
            POSTGRES_PASSWORD: ${PG_PASSWORD:?Missing environment variable see readme}
            POSTGRES_DB: ${PG_DB-atlassianCrowdProd}

networks:
    nginxproxynet:
        name: ${PROXY_NETWORK_NAME-nginxproxynet}
        external: true
